# Generated by Django 2.1.7 on 2019-03-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='user_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
